### ISSUE TITLE
Facing connection issue while creating new migration project in Exercise-1, Task-3

### ISSUE THREAD

**Issue by rcy0228** [microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure#2]
Hi, 
I am facing an issue while creating new migration project in Database Migration Service in [Exercise-1 Task-3 Step-4](https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Building%20the%20business%20migration%20case%20with%20Linux%20and%20OSS%20DB%20to%20Azure.md#task-3-migration-mysql-database-to-azure).  

Please find the Error details below with screenshot FYR:

```
{ "resourceId":"/subscriptions/resourceGroups/terrafirm-rg/providers/Microsoft.DataMigration/services/terrafirm-database-migration", "errorType":"Failed to connect, please check error details", "errorDetail":"Unable to collect server properties for server `20.14.185.2` due to a connection error.Connection failed.Host '20.12.78.67' is not allowed to connect to this MySQL server" }
```

![image](https://user-images.githubusercontent.com/104890759/209555880-5a88cde4-09d0-4dff-a5e0-b83f649ecd2b.png)

FYI, we have the required MYSQL port 3306 is enabled. Please find the below screenshot:

![image](https://user-images.githubusercontent.com/104890759/209556113-04e5a5b4-1756-43f8-b0cc-ca253206a598.png)

**Comment by daneenec** [comment]
@rcy0228 We will have a resource available next week to review this issue further.  Thank you!

**Comment by sumitmalik51** [comment]
Hi @daneenec ,
Seems like this is related to the permission from MySQL,

**Comment by crpietschmann** [comment]
@rcy0228 This error message means the MySQL user permissions aren't set correctly. I ran through things and it did work for me. When you performed the "Before the HOL" steps, when you got to Task 2, Step 4, were you able to login to the phpipam web application? If not, then it's possible the deployment scripts for the ARM Template errored. The deployment log for the Resource Group should show the deployment failed if this is the case. 

If the deployment script had errored somehow, then you'll need to delete the resources / resource group and run the "Before the HOL" deployment steps again. There's no way easily "fix" the "Before the HOL" deployment if it fails, and the easiest path is to just recreate it.

**Comment by DawnmarieDesJardins** [comment]
No additional comments, closing issue as resolved.  Feel free to reopen if necessary.
