### ISSUE TITLE
MySQL to Azure Database for MySQL Offline Data Migration Wizard

### ISSUE THREAD

**Issue by vycao412** [microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure#3]
Hi team,

I got the error:
_Unable to collect server properties for server `4.194.218.94` due to a connection error.
Connection failed.
Host '4.193.75.227' is not allowed to connect to this MySQL server_
when trying on the "MySQL to Azure Database for MySQL Offline Data Migration Wizard" page. (attached image below)

`4.194.218.94` for the VM

![image](https://user-images.githubusercontent.com/63325854/215458867-75db785d-cbda-4712-bbcd-1b09ef8b4cfa.png)

Could you help me to figure out?

Thanks.

**Comment by DawnmarieDesJardins** [comment]
@vycao412 
Thanks for letting us know.  I will assign one of our authors to review as soon as one becomes available.

**Comment by DawnmarieDesJardins** [comment]
Added Sarah for visibility.

**Comment by crpietschmann** [comment]
@vycao412 This error message means the MySQL user permissions aren't set correctly. When you performed the "Before the HOL" steps, when you got to Task 2, Step 4, were you able to login to the phpipam web application? If not, then it's possible the deployment scripts for the ARM Template errored. The deployment log for the Resource Group should show the deployment failed if this is the case.

If the deployment script had errored somehow, then you'll need to delete the resources / resource group and run the "Before the HOL" deployment steps again. There's no way to easily "fix" the "Before the HOL" deployment if it fails, and the easiest path is to just recreate it.

FYI, this is the same as Issue #2

**Comment by DawnmarieDesJardins** [comment]
@vycao412 
Hi Vy - Checking in to see if Chris has answered your question.  May we close this issue?  Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete.
