### ISSUE TITLE
Error MySQL to Azure Database for MySQL Offline Data Migration Wizard 

### ISSUE THREAD

**Issue by dongict95** [microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure#4]
I completed this step: https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Building%20the%20business%20migration%20case%20with%20Linux%20and%20OSS%20DB%20to%20Azure.md
and I logged in successfully to page: 
![image](https://user-images.githubusercontent.com/18282959/231680210-4306acc8-c4df-4b67-a39e-c69ceea51e13.png)
But when I come to step MySQL to Azure Database for MySQL Offline Data Migration Wizard . 
It still return error:
![image](https://user-images.githubusercontent.com/18282959/231680543-92a80289-e659-47f5-96f1-d67dc54a32da.png)

**Comment by crpietschmann** [comment]
This error message means the MySQL user permissions aren't set correctly. When you performed the "Before the HOL" steps, when you got to Task 2, Step 4, were you able to login to the phpipam web application? If not, then it's possible the deployment scripts for the ARM Template errored. The deployment log for the Resource Group should show the deployment failed if this is the case.

If the deployment script had errored somehow, then you'll need to delete the resources / resource group and run the "Before the HOL" deployment steps again. There's no way to easily "fix" the "Before the HOL" deployment if it fails, and the easiest path is to just recreate it.

FYI, this is the same as Issue #2

**Comment by DawnmarieDesJardins** [comment]
No further comments, closing this issue.

**Comment by GokhanSenyuz** [comment]
same error. Deployed 3 times and got no errors from deployments. I had no issues connecting phpipam application but still getting this error.

**Comment by DawnmarieDesJardins** [comment]
Reopening issue for further review.

**Comment by DawnmarieDesJardins** [comment]
Closing request with merge of PR #6  - additional instructions added to HOL.
