### ISSUE TITLE
SQL Connection Issue (Same old issue)

### ISSUE THREAD

**Issue by GokhanSenyuz** [microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure#5]
I completed this step: https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Building%20the%20business%20migration%20case%20with%20Linux%20and%20OSS%20DB%20to%20Azure.md
and I logged in successfully to ipam application.

Unable to collect server properties for server 4.194.218.94 due to a connection error.
Connection failed.
Host 'X.X.X.X' is not allowed to connect to this MySQL server
when trying on the "MySQL to Azure Database for MySQL Offline Data Migration Wizard" page. 

Re-Deployed 3 times and got no errors from deployments. I had no issues connecting phpipam application but still getting this error.

**Comment by DawnmarieDesJardins** [comment]
Closing request with merge of PR #6 - additional instructions added to HOL.
